### ISSUE TITLE
Create new README

### ISSUE THREAD

**Issue by 15sora2** [UMM-CSci-3601/lab1-on-html-and-css-lab1-omegasquad#4]
Create a new README listing and explaining the HTML5 & CSS3 features

**Comment by 15sora2** [comment]
Created OurREADME.md. Should look over it and add any information that you feel is missing @holma198

**Comment by holma198** [comment]
I have finished <ul> for the paw prints, and pushed it.  I didn't see
anything new in the readme, but i found out that calc() is css3 if that
helps.
